# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.3.22
forge_version_range=[47,)
loader_version_range=[47,)

tconstruct_version=3.9.0.6
tconstruct_version_range=[3.9.0.6,)

veinmining_version=1.3.0
veinmining_version_range=[1.3.0,)
# Can only get through CurseMaven
veinmining_fileid=5060090

mantle_version=1.11.28

mixin_version=0.8.5

mixin_extras_version=0.3.1
mixin_extras_version_range=[0.3.1,)

# The mapping channel to use for mappings.
mapping_channel=official
mapping_version=1.20.1


## Mod Properties

mod_id=tinkers_vein_miner
mod_name=Tinker's Vein Miner
mod_license=JSON
mod_version=1.0.0
mod_group_id=dev.ethy.tinkers_vein_miner
mod_authors=KaitlynEthylia
mod_description=Integrates the VeinMiner mod with Tinker's Construct as a modifier.
